on: 
  workflow_dispatch:
  
jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout
      - name: call wf
        uses: ./.github/workflows/test.yml