name: Check Caddy Version
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check for caddy_latest_release.txt
        run: touch caddy_latest_release.txt

      - name: Get latest Caddy version
        id: caddy-version
        run: |
          echo "CADDY_VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Compare versions and update file
        run: |
          if [[ "${{ env.CADDY_VERSION }}" != "$(cat caddy_latest_release.txt)" ]]; then
            echo "${{ env.CADDY_VERSION }}" > caddy_latest_release.txt
            echo "VERSION_UPDATED=true" >> $GITHUB_ENV
          else
            echo "VERSION_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Run another action
        if: steps.compare-versions.outputs.version-updated == 'true'
        run: echo "Running another action..."
