name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      caddy_release_tag:
        description: 'Caddy release tag to use for Docker image tag'
        required: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Read config.yml
        id: read-config
        run: |
          echo "packages=$(yq e '.packages[]' ./config.yml | paste -sd " ")" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: lower-repo
        name: Repository to lowercase
        run: echo "repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: packages=${{ steps.read-config.outputs.packages }}
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.event.inputs.caddy_release_tag }}